CREATE TABLE products (
  id  BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1) NOT NULL PRIMARY KEY,
  name varchar(64) NOT NULL,
  price decimal(15,2) NOT NULL,
  description varchar(255)
);

CREATE UNIQUE INDEX idx_products_name ON products(name);

CREATE TABLE users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1) NOT NULL PRIMARY KEY,
  userid varchar(64) NOT NULL,
  email varchar(64),
  passphrase varchar(100) NOT NULL,
  salt varchar(100) NOT NULL,
  date_created datetime NOT NULL,
  description varchar(255)
);

CREATE UNIQUE INDEX idx_users_userid ON users(userid);

CREATE TABLE roles (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1) NOT NULL PRIMARY KEY,
  description varchar(255),
  name varchar(50) NOT NULL
);

CREATE UNIQUE INDEX idx_roles_name ON roles(name);

CREATE TABLE role_permissions (
  role_id BIGINT NOT NULL,
  permission varchar(50) NOT NULL,
  PRIMARY KEY (role_id, permission),
  CONSTRAINT fk_role_id FOREIGN KEY (role_id) REFERENCES roles (id)
);

CREATE TABLE user_roles (
  user_id BIGINT NOT NULL,
  role_id BIGINT NOT NULL,
  PRIMARY KEY (user_id,role_id),
  CONSTRAINT fk_user_role_role_id FOREIGN KEY (role_id) REFERENCES roles (id),
  CONSTRAINT fk_user_role_user_id FOREIGN KEY (user_id) REFERENCES users (id)
);
