CREATE TABLE products (
  id  BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1) NOT NULL PRIMARY KEY,
  name varchar(64) NOT NULL,
  price decimal(15,2) NOT NULL,
  description varchar(255)
);

CREATE UNIQUE INDEX idx_products_name ON products(name);